#version: '3.7'

networks:
  inception:
    name: inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wp
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    env_file:
      - var.env
    networks:
      - inception
    volumes:
     - db_data:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file:
      - var.env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    restart: always
  
