#version: '3.7'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:42
    networks:
      - inception
    volumes:
     - db_data:/var/lib/mysql
    secrets:
      - dbname
      - dbpsw
      - dbusr
      - dbusrpsw
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    secrets:
      - dbname
      - dbhost
      - dbpsw
      - wpmngr
      - wpusr
      - wpusrpsw
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:42
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ./requirements/bonus/nodejs/app:/app
    restart: unless-stopped

  redis:
    depends_on:
      - nginx
      - wordpress
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:42
    networks:
      - inception
    secrets:
      - apikey
    restart: unless-stopped

  vsftp:
    depends_on:
      - wordpress
    container_name: vsftp
    build: ./requirements/bonus/vsftp
    image: vsftp:42
    networks:
      - inception
    ports:
      - "21:21"
    volumes:
      - wp_data:/var/www/html
    secrets:
      - wpusr
      - wpusrpsw
    restart: unless-stopped

  adminer:
    depends_on:
      - mariadb
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:42
    networks:
      - inception
    ports:
      - "8080:80"
    restart: unless-stopped

  netdata:
    depends_on:
      - nginx
      - redis
      - vsftp
      - wordpress
      - mariadb
      - adminer
    container_name: netdata
    build: ./requirements/bonus/netdata
    image: netdata:42
    networks:
      - inception
    ports:
      - "19999:19999"
    secrets:
      - apikey
    restart: unless-stopped

  nodejs:
    depends_on:
      - nginx
    container_name: nodejs
    build: ./requirements/bonus/nodejs
    image: nodejs:42
    networks:
      - inception
    volumes:
      - ./requirements/bonus/nodejs/app:/app
    restart: unless-stopped
  
networks:
  inception:
    name: inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/db
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wp
      o: bind

secrets:
  dbname:
    file: ../secrets/dbname.txt
  dbpsw:
    file: ../secrets/dbpsw.txt
  dbusr:
    file: ../secrets/dbusr.txt
  dbusrpsw:
    file: ../secrets/dbusrpsw.txt
  dbhost:
    file: ../secrets/dbhost.txt
  wpmngr:
    file: ../secrets/wpmngr.txt
  wpusr:
    file: ../secrets/wpusr.txt
  wpusrpsw:
    file: ../secrets/wpusrpsw.txt
  apikey:
    file: ../secrets/apikey.txt