#version: '3.7'

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./dependencies/mariadb
    image: mariadb:42
    env_file:
      - var.env
    networks:
      - inception
    volumes:
     - ./data:/var/lib/mysql
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./dependencies/wordpress
    image: wordpress:42
    env_file:
      - var.env
    networks:
      - inception
    volumes:
      - ./data:/var/www/html
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./dependencies/nginx
    image: nginx:42
    env_file:
      - var.env
    networks:
      - inception
    ports:
      - "80:80"
    volumes:
      - ./data:/var/www/html
    restart: always
  
