#version: '3.7'

networks:
  inception:
    name: inception

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dependencies/mariadb/data

services:

  nginx:
    container_name: nginx
    build: ./dependencies/nginx
    image: nginx:42
    env_file:
      - var.env
    networks:
      - inception
    ports:
      - "8080:80"
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./dependencies/mariadb
    image: mariadb:42
    env_file:
      - var.env
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always